name: Django Validator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

jobs:
  django-syntax-check:
    name: Django Syntax and Configuration Check
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: sqlite:///db.sqlite3
      SECRET_KEY: 'a-temporary-secret-key-for-testing'
      DEBUG: 'False'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Migrate Database Schema
        run: python manage.py migrate

      - name: Run Django Check
        run: python manage.py check
